#!/usr/bin/env python3
"""Join the OTel and Micrometer inventories and render the overlap / delta.

Inputs (all generated by the rest of this repo):
  - inventory/otel-<version>.json       (tools/extract_otel_inventory.py)
  - inventory/micrometer-*.json          (harness-tier* runs)
  - tools/concept_map.yaml               (curated cross-name equivalences)

Strategy (three layers, cheapest first):
  1. Exact-name join     - same metric name on both sides (e.g. jvm.memory.used). The tool decides
                           direct vs semantic from instrument-type and unit compatibility.
  2. Curated concept map - cross-name equivalences a human asserted (jvm.gc.duration <-> jvm.gc.pause).
  3. Leftovers = gaps    - unmatched on either side. A gap on a technology the Micrometer harness has
                           not captured yet is reported as "awaiting Tier N", NOT a true gap, so
                           harness coverage is never mistaken for a real Micrometer gap.

Outputs:
  - output/comparison-report.md   human-readable, per-technology tables + summary matrix
  - inventory/comparison.json     machine-readable join result

Usage:
    python3 tools/compare.py [--otel inventory/otel-v2.29.0.json] [--out output/comparison-report.md]
"""
import argparse
import glob
import json
import os
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent

# Which Micrometer capture tier is expected to populate each technology bucket. Used to label
# "OTel-only" rows that are really just un-captured Micrometer coverage rather than true gaps.
# Keep in sync with work-streams/05-micrometer-testbed.md coverage tiers.
EXPECTED_MM_TIER = {
    "jvm": 0, "system": 0, "executor": 0, "logging": 0,
    "cache": 1, "pool": 1, "netty": 1,         # Micrometer-only buckets captured at Tier 1
    "tomcat": 3, "spring": 3,                   # Micrometer-only buckets captured at Tier 3
    "db.pool": 1, "rpc": 2, "kafka": 2,
    "http.server": 3, "http.client": 2,
    # No Micrometer (core) equivalent → genuine OTel-only gaps, not pending harness coverage:
    "db.client": None, "messaging": None,
    "genai": None, "resilience": None, "iceberg": None,
}

# Prose caveats rendered under a bucket heading where the mechanical class would mislead.
BUCKET_NOTES = {
    "kafka": (
        "The OTel registry catalogs **no** `kafka.*` metrics — the agent's Kafka instrumentations "
        "emit spans only. The agent's Kafka *metrics* come from dynamically bridging the **same** "
        "Kafka client `metrics()` via its `KafkaMetrics` reporter (the bridge isn't represented as "
        "registry `metrics:` blocks). So these Micrometer metrics have agent equivalents at runtime "
        "— treat the rows below as **bridged / uncatalogued**, not a true Micrometer-only gap."
    ),
    "db.client": (
        "OTel times every DB operation (`db.client.operation.duration`). Micrometer **core** has no "
        "equivalent — the closest analog is Spring Data's `spring.data.repository.invocations` "
        "(per-repository-method timing, coarser granularity), not captured here. Treat as an OTel-only gap."
    ),
    "messaging": (
        "OTel emits messaging-semconv metrics (`messaging.*`, here from Pulsar). Micrometer has no "
        "general messaging-semconv binder — its messaging signal is either client-internal "
        "(`kafka.*`, see that bucket) or Spring observation timers (`spring.kafka.*`/`spring.rabbit.*`/"
        "JMS), none of which line up with `messaging.publish/receive.*`. Treat as an OTel-only gap."
    ),
}

# Micrometer Meter.Type -> set of compatible OTel `instrument` kinds.
MM_TYPE_TO_OTEL = {
    "COUNTER": {"counter"},
    "GAUGE": {"gauge", "updowncounter"},
    "TIMER": {"histogram"},
    "DISTRIBUTION_SUMMARY": {"histogram"},
    "LONG_TASK_TIMER": set(),
}

_UNIT_CANON = {
    "seconds": "s", "second": "s", "s": "s",
    "bytes": "by", "byte": "by", "by": "by",
    "ms": "ms", "ns": "ns", "1": "1",
}


def norm_unit(u):
    if not u:
        return None
    v = u.strip().strip("{}").lower()
    if v in _UNIT_CANON:
        return _UNIT_CANON[v]
    # loose singularization for annotation/count units: threads->thread, classes->class, ...
    if v.endswith("s") and len(v) > 1:
        v = v[:-1]
    return v


def load_micrometer():
    """Merge every inventory/micrometer-*.json into name-keyed records (micrometer variant only)."""
    by_name = {}
    files = sorted(glob.glob(str(REPO / "inventory" / "micrometer-*.json")))
    captured_tech = set()
    versions = set()
    for f in files:
        inv = json.load(open(f))
        versions.add(inv["header"].get("micrometerVersion"))
        for m in inv["meters"]:
            if m.get("conventionVariant") != "micrometer":
                continue  # the otel variant is an identity copy at tier 0; avoid double counting
            captured_tech.add(m["technology"])
            rec = by_name.setdefault(m["name"], {
                "name": m["name"], "meterTypes": set(), "units": set(),
                "technology": m["technology"], "emittedBy": set(), "tagKeys": set(),
                "deprecated": True,
            })
            rec["meterTypes"].add(m["meterType"])
            rec["units"].add(m.get("baseUnit"))
            rec["emittedBy"].add(m["emittedBy"])
            rec["tagKeys"].update(m.get("tagKeys") or [])
            rec["deprecated"] = rec["deprecated"] and m.get("deprecated", False)
    return by_name, captured_tech, sorted(v for v in versions if v), files


def load_otel(path):
    inv = json.load(open(path))
    # collapse per name (union the `when`/gate variants; e.g. jvm.memory.used default+Java17)
    by_name = {}
    for r in inv["meters"]:
        rec = by_name.get(r["name"])
        if rec is None:
            rec = dict(r)
            rec["whens"] = set()
            rec["gates"] = set()
            by_name[r["name"]] = rec
        rec["whens"].add(r["when"])
        rec["gates"].add(r["gate"])
    return inv["header"], by_name


def classify(otel_rec, mm_rec, hint=None):
    """direct | semantic | partial.

    A curated concept-map relation (hint) is authoritative — the curator can see attribute-model
    differences the type/unit check can't — except a `direct` claim is downgraded to `semantic` if
    the instrument types are actually incompatible (a safety net against a wrong map entry). Exact-name
    matches carry no hint and are classified from instrument-type + unit compatibility.
    """
    type_ok = any(otel_rec["instrument"] in MM_TYPE_TO_OTEL.get(t, set()) for t in mm_rec["meterTypes"])
    unit_ok = norm_unit(otel_rec.get("unit")) in {norm_unit(u) for u in mm_rec["units"]}
    if hint in ("direct", "semantic", "partial"):
        if hint == "direct" and not type_ok:
            return "semantic"
        return hint
    return "direct" if (type_ok and unit_ok) else "semantic"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    default_otel = sorted(glob.glob(str(REPO / "inventory" / "otel-*.json")))
    ap.add_argument("--otel", default=default_otel[-1] if default_otel else None,
                    help="OTel inventory JSON (default: latest inventory/otel-*.json)")
    ap.add_argument("--out", default=str(REPO / "output" / "comparison-report.md"))
    args = ap.parse_args()
    if not args.otel:
        raise SystemExit("no inventory/otel-*.json found; run tools/extract_otel_inventory.py first")

    mm, captured_tech, mm_versions, mm_files = load_micrometer()
    otel_header, otel = load_otel(args.otel)
    concept = yaml.safe_load(open(REPO / "tools" / "concept_map.yaml")) or {}
    pairs = concept.get("pairs", []) or []

    matched_otel, matched_mm = set(), set()
    matches = []  # (otel_name, mm_name, relation, origin)

    # layer 1: exact-name join
    for name in set(otel) & set(mm):
        rel = classify(otel[name], mm[name])
        matches.append((name, name, rel, "exact"))
        matched_otel.add(name)
        matched_mm.add(name)

    # layer 2: curated concept map (cross-name)
    for p in pairs:
        on, mn = p.get("otel"), p.get("micrometer")
        if on in otel and mn in mm and on not in ("",) and not (on in matched_otel and mn in matched_mm):
            rel = classify(otel[on], mm[mn], hint=p.get("relation"))
            matches.append((on, mn, rel, "concept-map"))
            matched_otel.add(on)
            matched_mm.add(mn)

    # layer 3: leftovers = gaps
    gap_otel = [otel[n] for n in otel if n not in matched_otel]
    gap_mm = [mm[n] for n in mm if n not in matched_mm]

    # ---- assemble per-bucket view ----
    buckets = sorted(set([otel[n]["technology"] for n in otel])
                     | set([m["technology"] for m in mm.values()])
                     | set(EXPECTED_MM_TIER))
    # multimaps: one OTel metric may map to several Micrometer metrics (and vice versa) — render
    # every pair rather than letting the last write win.
    matches_of_otel: dict[str, list] = {}
    matched_mm_names = set()
    for on, mn, rel, origin in matches:
        matches_of_otel.setdefault(on, []).append((mn, rel, origin))
        matched_mm_names.add(mn)

    def bucket_rows(bucket):
        rows = []
        for n, r in sorted(otel.items()):
            if r["technology"] != bucket:
                continue
            if n in matches_of_otel:
                for mn, rel, origin in matches_of_otel[n]:
                    m = mm[mn]
                    rows.append({
                        "otel": n, "micrometer": mn, "class": rel, "origin": origin,
                        "otelType": r["instrument"], "mmType": "/".join(sorted(m["meterTypes"])),
                        "otelUnit": r.get("unit"), "mmUnit": "/".join(sorted(str(u) for u in m["units"])),
                    })
            else:
                tier = EXPECTED_MM_TIER.get(bucket)
                covered = bucket in captured_tech
                cls = "gap-otel-only" if (covered or tier is None) else f"awaiting-mm-tier{tier}"
                rows.append({
                    "otel": n, "micrometer": "—", "class": cls, "origin": "—",
                    "otelType": r["instrument"], "mmType": "—",
                    "otelUnit": r.get("unit"), "mmUnit": "—",
                })
        # micrometer-only (no OTel equivalent)
        for n, m in sorted(mm.items()):
            if m["technology"] != bucket or n in matched_mm_names:
                continue
            rows.append({
                "otel": "—", "micrometer": n, "class": "gap-mm-only", "origin": "—",
                "otelType": "—", "mmType": "/".join(sorted(m["meterTypes"])),
                "otelUnit": "—", "mmUnit": "/".join(sorted(str(u) for u in m["units"])),
            })
        return rows

    report = {b: bucket_rows(b) for b in buckets}
    report = {b: rows for b, rows in report.items() if rows}

    # ---- machine-readable output ----
    comparison = {
        "otelVersion": otel_header.get("registryVersion"),
        "otelCommit": otel_header.get("registryCommit"),
        "micrometerVersions": mm_versions,
        "micrometerCaptureFiles": [os.path.basename(f) for f in mm_files],
        "capturedTechnologies": sorted(captured_tech),
        "buckets": report,
    }
    (REPO / "inventory" / "comparison.json").write_text(json.dumps(comparison, indent=2) + "\n")

    # ---- markdown report ----
    md = render_markdown(comparison, report)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(md)
    print(f"wrote {args.out} and inventory/comparison.json")
    print_summary(report, captured_tech)


def render_markdown(meta, report):
    L = []
    L.append("# Micrometer vs OpenTelemetry — metric comparison\n")
    L.append(f"- **OTel agent registry:** `{meta['otelVersion']}` @ `{meta['otelCommit']}`")
    L.append(f"- **Micrometer captures:** {', '.join(meta['micrometerCaptureFiles']) or '(none)'} "
             f"(version {', '.join(meta['micrometerVersions']) or '?'})")
    L.append(f"- **Captured technologies (Micrometer):** {', '.join(meta['capturedTechnologies']) or '(none)'}")
    L.append("\n> Generated by `tools/compare.py`. Classes: **direct** (same concept, compatible "
             "instrument+unit), **semantic** (concept matches, unit/instrument differs), **partial** "
             "(different granularity), **gap-otel-only** / **gap-mm-only**, **awaiting-mm-tierN** "
             "(OTel emits it; the Micrometer harness for that tier is not built yet — not a true gap).\n")

    # summary matrix
    L.append("## Summary\n")
    L.append("| Technology | OTel | MM | direct | semantic | partial | gap (OTel-only) | gap (MM-only) | awaiting MM |")
    L.append("|---|--:|--:|--:|--:|--:|--:|--:|--:|")
    for b, rows in report.items():
        c = {k: 0 for k in ("direct", "semantic", "partial", "gap-otel-only", "gap-mm-only", "awaiting")}
        n_otel = sum(1 for r in rows if r["otel"] != "—")
        n_mm = sum(1 for r in rows if r["micrometer"] != "—")
        for r in rows:
            cls = r["class"]
            if cls.startswith("awaiting"):
                c["awaiting"] += 1
            elif cls in c:
                c[cls] += 1
        L.append(f"| {b} | {n_otel} | {n_mm} | {c['direct']} | {c['semantic']} | {c['partial']} | "
                 f"{c['gap-otel-only']} | {c['gap-mm-only']} | {c['awaiting']} |")

    # per-bucket detail
    for b, rows in report.items():
        L.append(f"\n## {b}\n")
        if b in BUCKET_NOTES:
            L.append(f"> _Note:_ {BUCKET_NOTES[b]}\n")
        L.append("| OTel metric | Micrometer metric | class | OTel instr / unit | MM type / unit | via |")
        L.append("|---|---|---|---|---|---|")
        for r in rows:
            L.append(f"| `{r['otel']}` | `{r['micrometer']}` | {r['class']} | "
                     f"{r['otelType']} / `{r['otelUnit']}` | {r['mmType']} / `{r['mmUnit']}` | {r['origin']} |")
    return "\n".join(L) + "\n"


def print_summary(report, captured_tech):
    tot = {}
    for rows in report.values():
        for r in rows:
            cls = "awaiting-mm" if r["class"].startswith("awaiting") else r["class"]
            tot[cls] = tot.get(cls, 0) + 1
    print("captured MM technologies:", ", ".join(sorted(captured_tech)) or "(none)")
    for k in ("direct", "semantic", "partial", "gap-otel-only", "gap-mm-only", "awaiting-mm"):
        if k in tot:
            print(f"  {k:16} {tot[k]}")


if __name__ == "__main__":
    main()
